package com.qa.lamda.enums;

public enum ConfigProperties {
	
	LAMBDA_ENV,DEVHOST,QAHOST,LAMBDA_URL,USERNAME,PASSWORD,LOCATION,SELENIUMGRIDURL,BROWSER,BROWSER_VERSION,
	DATA_PROVIDER_THREAD_COUNT,HEADLESS,OVERRIDEREPORTS,PASSEDSTEPSSCREENSHOTS,FAILEDSTEPSSCREENSHOTS,
	RETRYFAILEDTESTS,RUNMODE,

}
